///////////////////////////////////////////////////////////////////////////////
// C1ClassFactory.cpp
#include "TcPch.h"
#pragma hdrstop

#include "C1ClassFactory.h"
#include "C1Services.h"
#include "C1Version.h"
#include "Module1.h"

BEGIN_CLASS_MAP(CC1ClassFactory)
///<AutoGeneratedContent id="ClassMap">
	CLASS_ENTRY_LIB(VID_C1, CID_C1CModule1, SRVNAME_C1 "!CModule1", CModule1)
///</AutoGeneratedContent>
END_CLASS_MAP()

CC1ClassFactory::CC1ClassFactory() : CObjClassFactory()
{
	TcDbgUnitSetImageName(TCDBG_UNIT_IMAGE_NAME_TMX(SRVNAME_C1));
#if defined(TCDBG_UNIT_VERSION)
	TcDbgUnitSetVersion(TCDBG_UNIT_VERSION(C1));
#endif //defined(TCDBG_UNIT_VERSION)
}

