///////////////////////////////////////////////////////////////////////////////
// C1Services.h

#pragma once

#include "TcServices.h"

const ULONG DrvID_C1 = 0x3F000000;
#define SRVNAME_C1 "C1"

///<AutoGeneratedContent id="ClassIDs">
const CTCID CID_C1CModule1 = {0x4f7f5a52,0xb010,0x490c,{0x8a,0x9d,0xc2,0xa6,0x19,0x90,0x2c,0x87}};
///</AutoGeneratedContent>

///<AutoGeneratedContent id="ParameterIDs">
///</AutoGeneratedContent>

///<AutoGeneratedContent id="DataTypes">
///</AutoGeneratedContent>



///<AutoGeneratedContent id="DataAreaIDs">
///</AutoGeneratedContent>

///<AutoGeneratedContent id="InterfaceIDs">
///</AutoGeneratedContent>

///<AutoGeneratedContent id="EventClasses">
///</AutoGeneratedContent>
