// C1W32.idl : IDL source for C1W32.dll
//

// This file will be processed by the MIDL tool to
// produce the type library (C1W32.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";
	[
		object,
		uuid(54EDF0AC-ACDE-4456-920E-A26D15A8503A),

		helpstring("IC1 Interface"),
		pointer_default(unique)
	]
	interface IC1Ctrl : IUnknown
	{
	};

[
	uuid(BF6DEC14-AD1A-44a6-82E2-5913CDE2288D),
	version(1.0),
	helpstring("C1W32 1.0 Type Library")
]
library C1W32Lib
{
	importlib("stdole32.tlb");
	importlib("stdole2.tlb");

	[
		uuid(F634CCE5-F3B1-47a9-8151-D2B004A4B8F3),
		helpstring("C1Ctrl Class")
	]
	coclass C1Ctrl
	{
		[default] interface IC1Ctrl;
	};
};
